# Generated by Django 3.0.5 on 2025-07-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='by',
        ),
    ]
